version: '3'
services:
  postgres:
    image: 'postgres'
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=app_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
