version: '3'
services:
  postgres:
    image: postgres
    ports:
    - "5000:5000"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=app_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data